name: flutter_libserialport
description: A simple wrapper around libserialport utilizing Flutter's
  build system to build and deploy the C-library for the target platform.
version: 0.5.3
homepage: https://github.com/jpnurmi/flutter_libserialport
repository: https://github.com/jpnurmi/flutter_libserialport
issue_tracker: https://github.com/jpnurmi/flutter_libserialport/issues

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  libserialport: ^0.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:   
  libserialport:
    git:
      url: https://github.com/AndreLuizNogueira/libserialport.dart.git

flutter:
  plugin:
    platforms:
      android:
        pluginClass: FlutterLibserialportPlugin
        package: org.sigrok.flutter_libserialport
      linux:
        pluginClass: FlutterLibserialportPlugin
      macos:
        pluginClass: FlutterLibserialportPlugin
      windows:
        pluginClass: FlutterLibserialportPlugin
